export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_GITHUB_PROFILE = 'GET_GITHUB_PROFILE';
export const GET_GITHUB_PROFILE_SUCCESS = 'GET_GITHUB_PROFILE_SUCCESS';

export const LOAD_GITHUB_PROFILE = 'LOAD_GITHUB_PROFILE';
export const LOAD_GITHUB_PROFILE_SUCCESS = 'LOAD_GITHUB_PROFILE_SUCCESS';